site_name: scrapy
site_url: https://oyemello.github.io/scrapy/
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
docs_dir: docs
nav:
  - Home: index.md
extra_css:
  - assets/overrides.css
