name: Sync Confluence and Deploy Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # daily at 07:00 UTC

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync and Deploy (v2)
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_EMAIL: ${{ secrets.CONFLUENCE_EMAIL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_ROOT_PAGE_ID: ${{ secrets.CONFLUENCE_ROOT_PAGE_ID }}
        run: |
          python scripts/sync_confluence.py
